name: example
description: Inception example app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  analyzer: ^6.4.1
  super_editor:
    git:
      url: git@github.com:superlistapp/super_editor.git
      path: super_editor/
  super_editor_markdown:
    git:
      url: git@github.com:superlistapp/super_editor.git
      path: super_editor_markdown/
  super_text_layout:
    git:
      url: git@github.com:superlistapp/super_editor.git
      path: super_text_layout/
  google_fonts: ^6.2.1
  flutter_highlight: ^0.7.0
  flutter_syntax_view: ^4.0.0
  syntax_highlight: ^0.4.0

  file_picker: ^8.1.2
  flutter_fancy_tree_view: ^1.6.0

  follow_the_leader: ^0.0.4+8
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  super_editor:
    git:
      url: git@github.com:superlistapp/super_editor.git
      path: super_editor/
  super_text_layout:
    git:
      url: git@github.com:superlistapp/super_editor.git
      path: super_text_layout/

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-VariableFont_wght.ttf
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-Italic-VariableFont_wght.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
